# Dùng bản Node alpine cho nhẹ
FROM node:18-alpine

WORKDIR /app

# Copy package và cài đặt
COPY package*.json ./
RUN npm install --production

# Copy toàn bộ code vào
COPY . .

# Mở port 3000 để K8s/Prometheus có thể gọi vào /health và /metrics
EXPOSE 3000

CMD ["node", "index.js"]