api:
  enabled: true
  image:
    repository: crypto-api
    tag: dev-k8s
  env:
    PRODUCTION: "true"
    PORT: "4000"
    PREFIX: "/api/v1"
    CLIENT_URL: "http://crypto.local"
  connectionSecret:
    enabled: true

web:
  enabled: true
  image:
    repository: crypto-web
    tag: dev-k8s
  env:
    NEXT_PUBLIC_URL: "http://crypto.local:8081"
    NEXT_PUBLIC_API_ENDPOINT: "http://crypto.local:8081/api/v1"
    NEXT_PUBLIC_WEBSOCKET_ENDPOINT: "ws://crypto.local:8081/api/v1"

ingestion:
  enabled: true
  image:
    repository: crypto-ingestion
    tag: dev-k8s
  env:
    SYMBOL: BTC/USDT

streaming:
  enabled: true
  image:
    repository: crypto-streaming
    tag: dev-k8s

batch:
  enabled: true
  image:
    repository: crypto-batch
    tag: dev-k8s
  kafkaToMinio:
    enabled: true
    schedule: "*/5 * * * *"
  volume24hToMongo:
    enabled: true
    schedule: "*/10 * * * *"

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: crypto.local
      paths:
        - path: /
          pathType: Prefix
          serviceName: web
          servicePort: 3000
        - path: /api
          pathType: Prefix
          serviceName: api
          servicePort: 4000

infra:
  redis:
    enabled: true
  mongodb:
    enabled: true
    database: crypto_analytics
    auth:
      username: admin
  kafka:
    enabled: true
    topic: market_events
  minio:
    enabled: true
    bucket: crypto-lake
  kafkaUi:
    enabled: true
    ingress:
      enabled: true
      className: traefik
      host: kafka-ui.crypto.local

redis:
  auth:
    enabled: true
  master:
    persistence:
      enabled: false

mongodb:
  persistence:
    enabled: false

kafka:
  image:
    registry: docker.io
    repository: bitnamilegacy/kafka
    tag: 4.0.0-debian-12-r10
  controller:
    persistence:
      enabled: false

minio:
  image:
    registry: docker.io
    repository: bitnamilegacy/minio
    tag: 2024.12.18-debian-12-r0
  console:
    enabled: false
  persistence:
    enabled: false
